name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install mkdocs mkdocs-material
      - name: Deploy mkdocs site
        run: |
          mkdocs gh-deploy --force
